import type { Region, ScoringTableEntry } from './common'
import type { GamePlatform } from './gamePlatforms'

export type { GamePlatform } from './gamePlatforms'

export type CompetitionStatus =
  | 'Draft'
  | 'Upcoming'
  | 'RegistrationOpen'
  | 'RegistrationClosed'
  | 'InProgress'
  | 'Completed'
  | 'Archived'
  | 'Cancelled'

export type RoundStatus = CompetitionStatus | 'ResultsLocked'

export type StageType = 'qualifier' | 'race_day' | 'final' | 'consolation' | 'practice' | 'custom'
export type SessionType = 'practice' | 'qualifying' | 'race'
export type ResultStatus = 'Finished' | 'DNF' | 'DNS' | 'DSQ'
export type RestartPolicy = 'none' | 'fixedInterval' | 'manual'
export type MergeRule = 'bestLapPerDriver' | 'bestResultPerDriver' | 'allClassifications'

export interface SessionGameConfig {
  track?: string
  trackLayout?: string
  cars?: string
  carGroup?: string
  cloudLevel?: number
  rain?: number
  weatherRandomness?: number
  ambientTemp?: number
  trackTemp?: number
  timeMultiplier?: number
  sunAngle?: number
  weatherGraphics?: string
  baseTempAmbient?: number
  variationAmbient?: number
  baseTempRoad?: number
  variationRoad?: number
  windSpeedMin?: number
  windSpeedMax?: number
  windDirection?: number
  windVariationDirection?: number
  formationLapType?: number
  preRaceWaitingTimeSeconds?: number
  sessionOverTimeSeconds?: number
  postQualySeconds?: number
  postRaceSeconds?: number
  isFixedConditionQualification?: boolean
  simracerWeatherConditions?: number
  pitWindowLengthSec?: number
  driverStintTimeSec?: number
  mandatoryPitstopCount?: number
  maxDriversCount?: number
  maxTotalDrivingTime?: number
  tyreSetCount?: number
  isRefuellingAllowedInRace?: boolean
  isRefuellingTimeFixed?: boolean
  isMandatoryPitstopRefuellingRequired?: boolean
  isMandatoryPitstopTyreChangeRequired?: boolean
  isMandatoryPitstopSwapDriverRequired?: boolean
  damageMultiplier?: number
  fuelRate?: number
  tyreWearRate?: number
  tcAllowed?: number
  absAllowed?: number
  stabilityAllowed?: boolean
  autoclutchAllowed?: boolean
  stabilityControlLevelMax?: number
  disableIdealLine?: boolean
  disableAutosteer?: boolean
  disableAutoGear?: boolean
  disableAutoClutch?: boolean
  disableAutoPitLimiter?: boolean
  disableAutoEngineStart?: boolean
  disableAutoWiper?: boolean
  disableAutoLights?: boolean
  forceVirtualMirror?: boolean
  legalTyres?: string
  startRule?: number
  racePitWindowStart?: number
  racePitWindowEnd?: number
  reversedGridRacePositions?: number
  raceExtraLap?: boolean
  tyreBlanketsAllowed?: boolean
  loopMode?: boolean
  qualifyStandingType?: number
  raceOverTime?: number
  allowedTyresOut?: number
  trackMedalsRequirement?: number
  safetyRatingRequirement?: number
  racecraftRatingRequirement?: number
  trackGripSessionStart?: number
  trackGripRandomness?: number
  trackGripLapGain?: number
  trackGripSessionTransfer?: number
}

export interface SessionResult {
  position: number
  driverId: string
  teamId?: string
  sessionId?: string
  splitNumber?: number
  totalTime?: string
  bestLap?: string
  lapsCompleted?: number
  gapToLeader?: string
  status: ResultStatus
  penalty?: string
  points?: number
}

export interface EntryListEntry {
  id: string
  driverId?: string
  driverName: string
  teamName?: string
  raceNumber: number
  carModel?: string
  ballastKg?: number
  restrictor?: number
  isServerAdmin?: boolean
  isAutoGenerated?: boolean
}

export interface Split {
  id: string
  splitNumber: number
  serverName?: string
  serverPassword?: string
  adminPassword?: string
  spectatorPassword?: string
  maxConnections?: number
  registerToLobby?: boolean
  udpPort?: number
  tcpPort?: number
  httpPort?: number
  lanDiscovery?: number
  maxCarSlots?: number
  isRaceLocked?: number
  isLockedPrepPhase?: number
  shortFormationLap?: number
  dumpLeaderboards?: number
  dumpEntryList?: number
  randomizeTrackWhenEmpty?: number
  allowAutoDQ?: number
  ignorePrematureDisconnects?: number
  pickupModeEnabled?: number
  lockedEntryList?: number
  votingQuorum?: number
  voteDuration?: number
  blacklistMode?: number
  clientSendIntervalHz?: number
  qualifyMaxWaitPerc?: number
  maxBallastKg?: number
  raceGasPenaltyDisabled?: number
  resultScreenTime?: number
  welcomeMessage?: string
  numThreads?: number
  sleepTime?: number
  udpPluginLocalPort?: number
  udpPluginAddress?: string
  authPluginAddress?: string
  centralEntryListPath?: string
  forceEntryList?: number
  entryList?: EntryListEntry[]
  results?: SessionResult[]
  resultsLockedAt?: string
}

export interface BopEntry {
  track: string
  carModel: number
  ballastKg: number
}

export interface Session {
  id: string
  type: SessionType
  name_zh: string
  name_en: string
  durationMinutes?: number
  raceDuration?: number
  raceDurationType?: 'time' | 'laps'
  dayOfWeekend?: number
  hourOfDay?: number
  timeMultiplier?: number
  waitTime?: number
  isOpen?: number
}

export interface AdvancementRule {
  sourceSessionId?: string
  metric: 'lapTime' | 'position' | 'manual'
  lapTimeMultiplier?: number
  limit?: number
  targetStageId?: string
  fallbackPolicy?: 'none' | 'fillNext'
}

export interface Stage {
  id: string
  roundId: string
  type: StageType
  name_zh: string
  name_en: string
  description_zh?: string
  description_en?: string
  startsAt: string
  endsAt: string
  gameConfig?: SessionGameConfig
  sessions: Session[]
  splits: Split[]
  bopEntries?: BopEntry[]
  eligibilitySource?: 'roundRegistration' | 'previousStageResult' | 'manualInvite'
  advancementRule?: AdvancementRule
  splitAssignmentRule?: string
  minEntries?: number
  awardsPoints?: boolean
  resultsLockAt?: string
}

export interface Round {
  id: string
  competitionId: string
  roundNumber?: number
  name_zh: string
  name_en: string
  description_zh?: string
  description_en?: string
  track?: string
  trackLayout?: string
  coverImage?: string
  registrationOpenAt: string
  registrationCloseAt: string
  cancelRegistrationDeadline?: string
  maxRegistrations?: number
  registrationOverride?: 'forceOpen' | 'forceClosed'
  stages: Stage[]
  currentRegistrations: number
  registeredDriverIds: string[]
  cancelledReason_zh?: string
  cancelledReason_en?: string
}

export interface CompetitionRuleset {
  accessRequirements_zh?: string
  accessRequirements_en?: string
  scoringTable?: ScoringTableEntry[]
  scoringNote_zh?: string
  scoringNote_en?: string
  resources_zh?: string
  resources_en?: string
  streamUrl?: string
}

export interface Competition {
  id: string
  isDemo?: boolean
  name_zh: string
  name_en: string
  description_zh: string
  description_en: string
  coverImage: string
  regions: Region[]
  game: GamePlatform
  carClass: string
  carList?: string[]
  timezone?: string
  resultLockWindowHours?: number
  minSplitEntries?: number
  defaultRuleset: CompetitionRuleset
  rounds: Round[]
  statusOverride?: 'Draft' | 'Cancelled' | 'Archived'
  cancelledReason_zh?: string
  cancelledReason_en?: string
  createdBy: string
  createdAt: string
  updatedAt: string
}

export function totalRegistrations(c: Competition): number {
  return c.rounds.reduce((sum, r) => sum + r.currentRegistrations, 0)
}
